services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      UVICORN_LOG_LEVEL: info
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
