[project]
name = "ng-2512"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask==3.0.3",
    "gunicorn==21.2.0",
    "pgvector==0.2.5",
    "psycopg[binary]==3.1.19",
    "pytest==8.3.3",
    "sqlalchemy==2.0.32",
]
