version: "3.9"

services:
  api:
    image: "${IMAGE_REPO}:${IMAGE_TAG}"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      FLASK_APP: ${FLASK_APP:-backend.app:create_app}
      DATABASE_URL: ${DATABASE_URL:-}
      REDIS_URL: ${REDIS_URL:-}
      VLLM_ENDPOINT: ${VLLM_ENDPOINT:-http://vllm:8008}
    ports:
      - "${HOST_PORT:-8000}:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      vllm:
        condition: service_started
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8000/healthz').read()",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: postgres:15-alpine
    profiles: ["postgres"]
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-recall}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-recall}
      POSTGRES_DB: ${POSTGRES_DB:-recall}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-recall}"]
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7-alpine
    profiles: ["redis"]
    restart: unless-stopped
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    ports:
      - "${REDIS_EXPOSE_PORT:-6379}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  vllm:
    image: python:3.11-slim
    profiles: ["vllm"]
    restart: unless-stopped
    command:
      [
        "python",
        "-c",
        "from http.server import BaseHTTPRequestHandler, HTTPServer\nclass Handler(BaseHTTPRequestHandler):\n    def do_GET(self):\n        self.send_response(200)\n        self.send_header('Content-Type', 'application/json')\n        self.end_headers()\n        self.wfile.write(b'{\"status\":\"ok\"}')\n    def log_message(self, *args, **kwargs):\n        return\nHTTPServer(('0.0.0.0', 8008), Handler).serve_forever()\n",
      ]
    ports:
      - "${VLLM_EXPOSE_PORT:-8008}:8008"

volumes:
  postgres-data:
